### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by scanhead** [angela-d/product-requests-opencart#1]
Not sure if this is because I updated but when i try and install it kicks up a server error, in the log i get 2018-04-22 19:13:48 - PHP Warning:  zip_read() expects parameter 1 to be resource, integer given in /var/www/vhosts/bbwars.co.nz/httpdocs/admin/controller/extension/installer.php on line 137
2018-04-22 19:13:48 - PHP Warning:  zip_close() expects parameter 1 to be resource, integer given in /var/www/vhosts/bbwars.co.nz/httpdocs/admin/controller/extension/installer.php on line 203

**Comment by angela-d** [comment]
That's a general Opencart error & not specific to Product Requests, so there's likely something else going on.  Can you install other extensions right now?

What version of Opencart are you running?

**Comment by scanhead** [comment]
2.3.0.3_rc Those were the only new errors in the log after install the error on the install page was very generic also., seems i can install other modules that are on the module install page, would you like me to down load a random module and test install?

**Comment by angela-d** [comment]
This one is from Product requests!

I'm a bit perplexed on how you got these
```html
PHP Warning: zip_read() expects parameter 1 to be resource, integer given in /var/www/vhosts/bbwars.co.nz/httpdocs/admin/controller/extension/installer.php on line 137
```
indicates something is up with your installer, particularly the zip function.  But it looks like it extracted anyway; hence these errors.


Since the install query insert was not triggered, the required tables are missing from your store:
```php
  public function install() {
		$this->db->query("CREATE TABLE `" . DB_PREFIX . "product_notification` (
			`id` int(11) AUTO_INCREMENT PRIMARY KEY,
		  `product_id` int(11),
		  `email` varchar(200) NOT NULL,
		  `token` varchar(255) DEFAULT NULL,
		  `confirmed` tinyint(1) NOT NULL DEFAULT '0',
		  `confirming_ip` varchar(40) NOT NULL,
		  `date` datetime NOT NULL,
			`language_code` varchar(11) NOT NULL
		) ENGINE=MyISAM DEFAULT CHARSET=latin1;

			ALTER TABLE `" . DB_PREFIX . "product_notification`
			  ADD KEY `pid` (`product_id`);
		");

		$this->model_user_user_group->addPermission($this->user->getGroupId(), 'access', 'extension/module/' . $this->request->get['extension']);
		$this->model_user_user_group->addPermission($this->user->getGroupId(), 'modify', 'extension/module/' . $this->request->get['extension']);

		$this->model_user_user_group->addPermission($this->user->getGroupId(), 'access', 'report/product_request');
		$this->model_user_user_group->addPermission($this->user->getGroupId(), 'modify', 'report/product_request');

		$this->model_user_user_group->addPermission($this->user->getGroupId(), 'access', 'report/product_request_detail');
		$this->model_user_user_group->addPermission($this->user->getGroupId(), 'modify', 'report/product_request_detail');
	}
```

To fix this and get back into your admin, open phpmyadmin from your cPanel admin, click your store's database name and then click the SQL tab.
**REPLACE *YOURPREFIX_* with the db prefix of your database rows, most commonly it is oc_**
To know what your prefix is, see what the first few letters of each table in phpmyadmin are.  It's set during install and can be customized, so it varies from site to site.

Paste this into the SQL textarea:
```mysql
CREATE TABLE `YOURPREFIX_product_notification` (
			`id` int(11) AUTO_INCREMENT PRIMARY KEY,
		  `product_id` int(11),
		  `email` varchar(200) NOT NULL,
		  `token` varchar(255) DEFAULT NULL,
		  `confirmed` tinyint(1) NOT NULL DEFAULT '0',
		  `confirming_ip` varchar(40) NOT NULL,
		  `date` datetime NOT NULL,
			`language_code` varchar(11) NOT NULL
		) ENGINE=MyISAM DEFAULT CHARSET=latin1;

			ALTER TABLE `YOURPREFIX_product_notification`
			  ADD KEY `pid` (`product_id`);
```

**Comment by scanhead** [comment]
Okay, ill give it a go but its been a while since I did any SQL. Im using myphpadmin, looking at it the prefix is "oc_". Im going to assume that im entering this info into the text area in on the SQL tab? I also did a bad and deleted one of the tpl files in an attempt to uninstall the module, im not to crash hot at opencart. so ill need to replace that, hoping its in the mod zip.

**Comment by scanhead** [comment]
Thanks, im back in. The module will install, but i can edit it, just get a 500 error. Here are the logs.

[Fri Apr 27 08:32:04 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: PHP Fatal error:  Can't use method return value in write context in /var/www/vhosts/bbwars.co.nz/httpdocs/admin/controller/extension/module/product_request.php on line 114, referer: http://www.bbwars.co.nz/admin/index.php?route=extension/extension&token=hzHt1obhfUZ0QMSXtxduU1aiPonBetHw
[Fri Apr 27 08:32:07 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: PHP Fatal error:  Can't use method return value in write context in /var/www/vhosts/bbwars.co.nz/httpdocs/admin/controller/extension/module/product_request.php on line 114
[Fri Apr 27 08:33:11 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: PHP Fatal error:  Can't use method return value in write context in /var/www/vhosts/bbwars.co.nz/httpdocs/admin/controller/extension/module/product_request.php on line 114, referer: http://www.bbwars.co.nz/admin/index.php?route=extension/extension&token=hzHt1obhfUZ0QMSXtxduU1aiPonBetHw

**Comment by angela-d** [comment]
Line 114 is checking the config status from the settings table of the database:
```php
} elseif (!empty($this->config->get('product_request_status'))) {
```
This mechanism is native to Open cart and returns null if nothing is there:
```php
	public function get($key) {
		return (isset($this->data[$key]) ? $this->data[$key] : null);
	}
```

I would have to say this extension is incompatible with the _rc release, so the best course of action is to uninstall it.

You can disable it from your admin panel and delete any of the files it installed; as well as delete that database table you manually installed.

For a test, I installed it to a fresh 2.3.0.2 shop and installed -> enabled and switched some statuses on.  Worked without a hitch.

_rc versions are release candidate / beta versions, so the code can change drastically between the prior version and next release.  _rc versions are mostly for testing and not really meant for production use, unfortunately.

My advice is if you want to use this extension, migrate your shop to 2.3.0.2 or see if there are others that might be compatible with the _rc version in the Opencart Marketplace.

**Comment by scanhead** [comment]
Okay, i downgraded the system and installed the module again, but i think it has the same problem:

[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: PHP Fatal error:  Uncaught Exception: Error: Could not load model report/product_request! in /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/storage/modification/system/engine/loader.php:59, referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: Stack trace:, referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: #0 /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/storage/modification/admin/controller/catalog/product.php(763): Loader->model('report/product_...'), referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: #1 /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/storage/modification/admin/controller/catalog/product.php(126): ControllerCatalogProduct->getForm(), referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: #2 /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/storage/modification/system/engine/action.php(51): ControllerCatalogProduct->edit(), referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: #3 /var/www/vhosts/bbwarsnz.com/httpdocs/upload/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array), referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: #4 /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/storage/modification/system/engine/action.php(51): ControllerStartupRouter->index(), referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: #5 /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/engine/front.php(34): Action->execute(Object(Registry)), referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:46 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: #6 /va in /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/storage/modification/system/engine/loader.php on line 59, referer: http://www.bbwarsnz.com/admin/index.php?route=catalog/product&token=Qbzs9jC0rNXc6xRGV0Jqck7cYTDv3KjQ
[Sun Apr 29 13:20:49 2018] [warn] [client 203.97.164.74] mod_fcgid: stderr: PHP Fatal error:  Uncaught Exception: Error: Could not load model report/product_request! in /var/www/vhosts/bbwarsnz.com/httpdocs/upload/system/storage/modification/system/engine/loader.php:59

I tried the same fix but got this error:

Error
Static analysis:

2 errors were found during analysis.

Unexpected beginning of statement. (near "REATE" at position 0)
Unrecognized statement type. (near "TABLE" at position 6)
SQL query:

REATE TABLE `oc_product_notification` ( `id` int(11) AUTO_INCREMENT PRIMARY KEY, `product_id` int(11), `email` varchar(200) NOT NULL, `token` varchar(255) DEFAULT NULL, `confirmed` tinyint(1) NOT NULL DEFAULT '0', `confirming_ip` varchar(40) NOT NULL, `date` datetime NOT NULL, `language_code` varchar(11) NOT NULL ) ENGINE=MyISAM DEFAULT CHARSET=latin1

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'REATE TABLE `oc_product_notification` (
            `id` int(11) AUTO_INCREMENT PRIMARY ' at line 1

If I fix it again, im not going to attempt this again. Im obviously doing something wrong every time.

**Comment by angela-d** [comment]
> mod_fcgid: stderr: PHP Fatal error: Uncaught Exception: Error: Could not load model report/product_request!

Indicates the model wasn't loaded to the modification folder.  This should occur while you upload the package in the extension installer.

If you're installing the files manually, you missed the one in **admin/model/report**/product_request.php

```mysql
Unexpected beginning of statement. (near "REATE" at position 0)
```
The `C` is missing from the create statement, did you run the query manually?

**Comment by scanhead** [comment]
I installed using the installer file and yes i ran the query manually. Not sure how that c went missing.

**Comment by angela-d** [comment]
You don't need to run the query manually if you enable the extension from ui.

Have you followed all of the steps from the [install instructions](../blob/master/installing-instructions.md)?

This step:
> Enable Product Request Extension by going to Extensions (left navigation menu; then clicking the green button to the right of Product Requests)

will run that query automatically for you.
